require("arch-err.remap")
require("arch-err.set")
require('neoscroll').setup()
require('nvim-lastplace').setup()
require('gitsigns').setup()
require('noice').setup()
require("ibl").setup()
require("various-textobjs").setup({ useDefaultKeymaps = true })
require("conform").setup()
require("trim").setup()
require("auto-save").setup()


-- require("bufferline").setup()
-- require('ufo').setup()
